#! /bin/bash

cd $(dirname ${BASH_SOURCE})
cd ..
REPO=$PWD

PACKAGES=(petsc py-petsc4py)
for PACKAGE in "${PACKAGES[@]}"; do
    cp -r $SPACK_ROOT/var/spack/repos/builtin/packages/$PACKAGE $REPO/packages/$PACKAGE
    patch $REPO/packages/$PACKAGE/package.py -i $REPO/share/$PACKAGE.patch
done
