#! /bin/bash

cd $(dirname ${BASH_SOURCE})
cd ..
REPO=$PWD

mv $REPO/packages/petsc $REPO/packages/petsc.orig
cp -r $SPACK_ROOT/var/repos/builtin/packages/petsc $REPO/packages/petsc

patch $REPO/packages/petsc/package.py -i $REPO/share/petsc.patch

